// Puts the example files into data.js, so index.html opens straight from disk (a page opened
// as a file cannot fetch its neighbours). Run it after changing anything in ../examples:
//
//   node proposals/planner/mock/build.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../examples/plannings/', import.meta.url);
const files = {};
for (const name of readdirSync(dir).sort()) {
  if (name.endsWith('.md') && name !== 'README.md') files[name] = readFileSync(new URL(name, dir), 'utf8');
}
const out = `/* Generated by build.mjs from ../examples/plannings: do not edit by hand. */\nwindow.PLANNER_FILES = ${JSON.stringify(files, null, 2)};\n`;
writeFileSync(new URL('data.js', import.meta.url), out);
console.log(`data.js: ${Object.keys(files).join(', ')}`);
