//! The typed bridge (L9): every command of commands.rs, collected by tauri-specta, which both
//! registers them with Tauri (`builder().invoke_handler()`) and writes the TypeScript the kernel
//! imports (`src/core/bridge/bindings.ts`). One list, so a command cannot be registered and
//! missing from the bindings, or the other way round.
//!
//! Each command's JS name is the camelCase of its Rust name, and answers
//! `{status: 'ok', data} | {status: 'error', error: HostError}`. Integers are exported as
//! `number` (the host's are file sizes, times in milliseconds and counters, far below 2^53).
//!
//! The bindings are generated, never edited: `bindings_are_current` renders them and compares
//! with the file, and `OSE_WRITE_BINDINGS=1 cargo test bindings` rewrites it.

use serde::Serialize;
use specta::Type;
use tauri_specta::{collect_commands, Builder, ErrorHandlingMode};

use crate::commands::*;

/// Where the bindings live, from the crate's folder.
pub const BINDINGS: &str = "../src/core/bridge/bindings.ts";

/// The first line of the file.
const HEADER: &str = "// Generated by the host (src-tauri/src/bindings.rs) with tauri-specta. Do not edit:\n// `OSE_WRITE_BINDINGS=1 cargo test bindings` in src-tauri writes it again.";

/// One change of the `fs` event.
#[derive(Debug, Clone, Serialize, Type)]
pub struct FsChange {
    /// A vault path, or `abs:` for an outside file this window opened.
    pub path: String,
    /// `create`, `modify`, `delete` or `rename`.
    pub kind: String,
    #[specta(optional)]
    pub to: Option<String>,
    #[specta(optional)]
    pub dir: Option<bool>,
    #[specta(optional)]
    pub hidden: Option<bool>,
}

/// The `fs` event, sent to its own window only.
#[derive(Debug, Clone, Serialize, Type)]
pub struct FsEvent {
    pub changes: Vec<FsChange>,
    /// The vault folder itself went away (`true`) or came back (`false`).
    #[specta(optional)]
    pub lost: Option<bool>,
    /// Something may have been missed: re-read what is shown.
    #[specta(optional)]
    pub rescan: Option<bool>,
}

/// Every command, and the event payloads the page listens for by hand.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            root_info,
            vault_info,
            pick_vault,
            open_vault,
            open_vault_window,
            recent_vaults,
            forget_vault,
            platform,
            quit,
            log,
            tree,
            list,
            stat,
            exists,
            search,
            read_text,
            read_file,
            save_file,
            create_new,
            create_new_binary,
            copy_file,
            import_outside,
            append_line,
            replace_line,
            write_text,
            append_text,
            write_binary,
            read_binary,
            mkdir,
            rename,
            copy_path,
            trash,
            trash_where,
            trash_list,
            trash_restore,
            draft_write,
            draft_list,
            draft_read,
            draft_drop,
            version_keep,
            version_list,
            version_read,
            version_restore,
            get_state,
            set_state,
            local_get,
            local_set,
            open_external,
            open_path,
            reveal,
            print_to_pdf,
            show_print_u_i,
            outside_open,
            take_opens,
            pick_file,
        ])
        .typ::<crate::HostError>()
        .typ::<FsEvent>()
        .typ::<crate::windows::OpenEvent>()
        .error_handling(ErrorHandlingMode::Result)
        .dangerously_cast_bigints_to_number()
}

/// The bindings as the exporter writes them, read back from a scratch file.
pub fn render() -> Result<String, String> {
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let n = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!("ose-bindings-{}-{n}", std::process::id()));
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let file = dir.join("bindings.ts");
    builder()
        .export(specta_typescript::Typescript::default().header(HEADER), &file)
        .map_err(|e| e.to_string())?;
    let text = std::fs::read_to_string(&file).map_err(|e| e.to_string());
    let _ = std::fs::remove_dir_all(&dir);
    // One line ending, whatever the platform wrote.
    text.map(|t| t.replace("\r\n", "\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The kernel's bindings are what these commands say. A command added, removed or changed
    /// without writing them again fails here, on every platform, in CI.
    #[test]
    fn bindings_are_current() {
        let fresh = render().expect("the bindings render");
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(BINDINGS);
        if std::env::var_os("OSE_WRITE_BINDINGS").is_some() {
            std::fs::write(&path, &fresh).expect("write the bindings");
            return;
        }
        let on_disk = std::fs::read_to_string(&path).unwrap_or_default().replace("\r\n", "\n");
        assert!(
            on_disk == fresh,
            "src/core/bridge/bindings.ts is out of date: run `OSE_WRITE_BINDINGS=1 cargo test bindings` in src-tauri"
        );
    }

    /// Every command answers the Result shape, under its old rpc name.
    #[test]
    fn the_names_are_the_page_s() {
        let fresh = render().expect("the bindings render");
        for name in ["readFile", "saveFile", "createNewBinary", "showPrintUI", "outsideOpen", "takeOpens", "trashWhere", "platform", "log"] {
            assert!(fresh.contains(&format!("	{name}: (")), "{name} is missing from the bindings");
        }
        assert!(fresh.contains("export type HostError"), "HostError is exported");
        assert!(!fresh.contains("bigint"), "numbers are numbers");
    }
}
